[linux] fix unit-test issue because USER and HOME are not set
--- FAIL: TestCredentialNoSetGroups (0.00s)
    exec_posix_test.go:20: error getting current user: user: Current not implemented on linux/amd64
FAIL
FAIL    os/exec 0.422s
ok      os/signal       4.476s
--- FAIL: TestCurrent (0.00s)
    user_test.go:37: Current: user: Current not implemented on linux/amd64 (got (*user.User)(nil))
--- FAIL: TestLookup (0.00s)
    user_test.go:80: Current: user: Current not implemented on linux/amd64
--- FAIL: TestLookupId (0.00s)
    user_test.go:101: Current: user: Current not implemented on linux/amd64
FAIL
FAIL    os/user 0.002s